### ISSUE TITLE
using vscode remote wsl development on wsl2-ubuntu20.04 , extention no response

### ISSUE THREAD

**Issue by kirk-zhang58** [mysql/mysql-shell-plugins#10]
click create new mysql connection with no response

OS: Ubuntu 20.04.4 LTS on Windows 10 x86_64
Kernel: 5.10.102.1-microsoft-standard-WSL2
Uptime: 9 hours, 40 mins
Packages: 1874 (dpkg)
Shell: bash 5.0.17
Theme: Adwaita [GTK3]
Icons: Adwaita [GTK3]
Terminal: /dev/pts/0
CPU: 11th Gen Intel i5-11300H (8) @ 3.110GHz
GPU: d633:00:00.0 Microsoft Corporation Device 008e
Memory: 1044MiB / 7839MiB

**Comment by mike-lischke** [comment]
This is an old issue and quite a few releases went out in the meantime. Can you please check again if this works for you now?
