### ISSUE TITLE
Export/Import or Sync Connections

### ISSUE THREAD

**Issue by byjg** [mysql/mysql-shell-plugins#12]
Is there a way to export/import the connections I have so I can use them in another VSCode install I have?

Or, even better, If add the feature of Sync connections?

**Comment by mike-lischke** [comment]
The connections are held in the MySQL shell user data. Check your homedir for a hidden folder named `.mysqlsh-gui`. In that folder there's the plugin data (`.mysqlsh-gui/plugin_data/gui_plugin/mysqlsh_gui_backend.sqlite3`). Not exactly an export, but at least you can save the connections as SQL and import them in a different machine. At at later point in time we will also add a regular export of the connections.
