### ISSUE TITLE
Formatter/beautifier not yet working

### ISSUE THREAD

**Issue by jankap** [mysql/mysql-shell-plugins#14]
Is the "format current block" button already supposed to work? 
![image](https://user-images.githubusercontent.com/12893844/196446342-a20ae0cf-877b-40e1-a487-2e42222de8e9.png)

If I press it, nothing happens yet.

Is there any information which engine is used? Is the formatting capability integrated in mysql-shell by any chance? I'd love to use mysql-shell in a CI/CD environment and auto-pre format sql files before comparing them. That's especially interesting for stored procedures.

Thank you very much.

**Comment by mike-lischke** [comment]
The beautifier currently only works for TS/JS code. There's no formatter yet for SQL code.
