### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ArmoredPony** [mysql/mysql-shell-plugins#18]
On startup, the extension starts "mysqlh.exe" process (even if I didn't open the extension panel in the first place), that initially takes about 36 MB of memory.
On the extension panel, every time when I press the "Open the DB connection browser" button this process takes ~1.5 MB of additional memory. When I press the "Reload the connection list" button this process takes ~0.2 MB of additional memory. Most of this memory is not released until VS Code is closed.
I wrote a PowerShell script that presses the second button 10000 times. After each execution, the process takes about 1500 MB of additional memory. Eventually, the system runs out of memory and VS Code crashes.
I don't think someone will actually press these buttons 10000 times, and this problem might not even be caused by the extension, but it might be good to let you know.
OS: Windows 10.0.19045
VS Code: 1.75.1

**Comment by mike-lischke** [comment]
Thanks for collecting that information. The web application is pretty large (lots of data files and a number of parsers), which explains why it is so large (1.5MB for a web app is huge, but that's the price for the functionality).

When you reload the connections where is the memory increase actually: in the MySQLShell process or VS Code?

**Comment by mike-lischke** [comment]
@rennox might be something in the GUI plugin BE...

**Comment by mike-lischke** [comment]
Should be fixed with the last releases.
