### ISSUE TITLE
Clear the console

### ISSUE THREAD

**Issue by Eitheages** [mysql/mysql-shell-plugins#22]
How can clear the notebook history on the screen?

Just like `\! clear` command on a real shell.

**Comment by mbodzek** [comment]
Hi @Eitheages

It's pretty easy, just hold down the `CTRL` key (on macOS `CMD` key) and press the `A` key twice quickly, this will select all statements on the notebook:
<img width="890" alt="Zrzut ekranu 2023-04-14 o 09 33 57" src="https://user-images.githubusercontent.com/10705489/231975677-edd26577-ac46-4486-aaf8-cddf17f4d96f.png">
Then press `DEL` key. After that all statements and outputs will be deleted.
