### ISSUE TITLE
Does MySQL Shell GUI create databases using my connection?

### ISSUE THREAD

**Issue by byjg** [mysql/mysql-shell-plugins#23]
I noticed yesterday a new database `mysql_rest_service_metadata` was created without my notice. This database has tables and functions. After creating this database, it was replicated to my backup DB and broke the replication of my production environment entirely. 

Unfortunately, I found code you are using this DB: https://github.com/search?q=repo%3Amysql%2Fmysql-shell-plugins%20mysql_rest_service_metadata&type=code

So, WHERE can I DISABLE IT? 

Also, it is a severe issue to make unadvertised change to the Database without my knowledge.

**Comment by mzinner** [comment]
Hi @byjg ,
We are very sorry for the issues you ran into on your production database.

The schema `mysql_rest_service_metadata` should not have been created automatically. The only way it should be created is by doing an explicit right-clicking onto a DB Connection in the DATABASE CONNECTIONS view and select `Configure Instance for MySQL REST Service Support`.

We need to find out what caused the automatic creation of the schema `mysql_rest_service_metadata` on your system.

Are you absolutely sure you did not select the popup menu option above when e.g. reviewing the new features of the extension?

Could you share the replication errors you got that caused replication to stop?

We would really appreciate your input on reproducing the error.

Thanks,
Mike

**Comment by rennox** [comment]
Hi @byjg 

A new release 1.10.1 is available with the fix to prevent the automatic deployment of the MRS schema.

To prevent accidental deployment by clicking the `Configure Instance for MySQL REST Service Support` a confirmation dialog is shown before proceeding to the deployment.

Thanks for bringing up this problem! And sorry for the inconvenience.
