### ISSUE TITLE
Broken SELECT output

### ISSUE THREAD

**Issue by a-b-e-q** [mysql/mysql-shell-plugins#24]
Here, I'm trying to view all of the rows for a certain table, but on DB Notebook the output is broken:
![mysql_vscode_result](https://user-images.githubusercontent.com/27394198/235362965-d045b162-e6bf-42fc-afd7-8a4d39a957df.png)
Compare this to the MySQL workbench output:
![mysql_workbench_result](https://user-images.githubusercontent.com/27394198/235362968-e597a1c2-51e3-423f-8c61-8e2a00554308.png)

Interestingly, I have start_time and end_time columns in my table, and they display fine on MySQL Workbench, but on DB Notebook they don't:
![image](https://user-images.githubusercontent.com/27394198/235363179-7b184612-ab5d-4e75-b976-73923e0dda7a.png)
![image](https://user-images.githubusercontent.com/27394198/235363188-28090838-3b35-437b-8e50-59e207392fc1.png)

**Comment by mike-lischke** [comment]
Would be good to see the table DDL, at least the columns that are not shown properly.

**Comment by mike-lischke** [comment]
This is how it looks currently. What's wrong with it?

<img width="913" alt="Bildschirmfoto 2023-05-02 um 09 23 56" src="https://user-images.githubusercontent.com/2398704/235604828-c8bfe145-c066-4791-a231-addf36c3436a.png">

**Comment by a-b-e-q** [comment]
> Would be good to see the table DDL, at least the columns that are not shown properly.

(sorry for the late reply, I unfortunately forgot that I opened this issue...)

```sql
DROP TABLE IF EXISTS /*redacted*/;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE /*redacted*/ (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `main_picture` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `recurrences` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  /*redacted*/ varchar(7) COLLATE utf8mb4_unicode_ci NOT NULL,
  `end_time` time(6) NOT NULL,
  `start_time` time(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=72 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
```

**Comment by mike-lischke** [comment]
Should be fixed with the last release.
