### ISSUE TITLE
Can't paste password

### ISSUE THREAD

**Issue by ZsoltPath** [mysql/mysql-shell-plugins#39]
I don't want (not allowed) to store the password in the plugin, I'd like to cope-paste it from my password manager.
When opening a connection the plugin doesn't allow to paste the password to the field. I can only type directly.

**Comment by ischia-exigenter** [comment]
Yeah, this is silly. Please don't disable the ability to copy & paste. Uncool.

**Comment by j00bar** [comment]
On Mac OS I can't paste _anything_ into the connection dialog - typing in the random amazonaws.com hostname is not fun either.

**Comment by aprilmintacpineda** [comment]
Seriously, why?

**Comment by mike-lischke** [comment]
That was a regression, sorry. A fix will be available with the next release.
