### ISSUE TITLE
Do you have plan to migrate this plugin to Azure Data Studio?

### ISSUE THREAD

**Issue by tonyqus** [mysql/mysql-shell-plugins#4]
According to https://github.com/microsoft/azuredatastudio/issues/4904, there are huge requests asking for mysql support on Azure Data Studio. I'm not sure if you have plan to migrate this plugin to Azure Data Studio?

**Comment by mike-lischke** [comment]
There are no plans to write a plugin for the Azure Data Studio currently. This extension makes use of the MySQL Shell functionality to provide its services (standard MySQL server work, MySQL Database Services (OCI) and MySQL REST Services), which in turn are implemented as MySQL Shell plugins. So, a natural approach for MySQL Azure support would be to write a MySQL Shell plugin, which does all the communication and let this extension handle the presentation.
