### ISSUE TITLE
Will there be compatibility for Arch Linux?

### ISSUE THREAD

**Issue by RafaelMoreira1180778** [mysql/mysql-shell-plugins#5]
Currently I cannot install the certificate needed since I am using Arch Linux.

Will there be compatibility with Arch Linux in the near future?

**Comment by mike-lischke** [comment]
Please try the new release from yesterday. It has some fixes related to certificate handling. Maybe that works for you now.

**Comment by rennox** [comment]
Hi @RafaelMoreira1180778 

I reviewed Arch Linux and it seems there's an unmet dependency for the MySQL Shell which basically prevents the extension to work.

We will review the possibility to solve this problem, and let you know once we have news about it.

**Comment by RafaelMoreira1180778** [comment]
@mike-lischke this is the Output for MySQL Shell for VSCode:

```log
Starting embedded MySQL Shell, using config dir '/home/rafael/.mysqlsh-gui' ...
Please enter the single instance token: 
10:16:17.697906 INFO: Token read from STDIN
10:16:17.698078 INFO: Starting MySQL Shell GUI web server...

10:16:17.698767 INFO: 	Checking web server certificate...

10:16:17.699678 INFO: 	Certificate is installed.

10:16:17.727001 INFO: 	Port: 45097
10:16:17.727144 INFO: 	Secure: True
10:16:17.727177 INFO: 	Webroot: /home/rafael/.vscode/extensions/oracle.mysql-shell-for-vs-code-1.2.1-linux-x64/shell/lib/mysqlsh/plugins/gui_plugin/core/webroot
10:16:17.727204 INFO: 	Mode: Single user

10:16:17.771219 INFO: Websocket connected
10:16:17.771714 INFO: Registering session...
10:16:17.782112 INFO: Sending session response...
```

**Comment by rennox** [comment]
Hi @RafaelMoreira1180778 

For the record, we use a generic linux shell package and it is expected that the system meets specific requirements, in the case of ArchLinux it no longer contains libcrypt.so.1 which would cause the Shell not to run, anyone willing to run the extension will have to satisfy this dependency, for what I verified, it is successfully met by installing the libxcrypt-compat package.

Considered you managed to get the certificate "installed" it means you already fixed this, however, there was still a problem specific to ArchLinux in relation to the certificate deployment.

The new version of the extension (1.0.3) fixes the problem, expectation is that it should work in Arch Linux this time.

Please let us know if it worked for you!

rennox

**Comment by RafaelMoreira1180778** [comment]
Hello @rennox, I am now receiving this error:

```log
12:34:30.564863 DEBUG: The certificate installation is inconsistent:
12:34:30.564887 DEBUG: USER_HOME: /home/rafael/.mysqlsh-gui/plugin_data/gui_plugin/web_certs/rootCA.crt, [Installed: True, Valid: True]
12:34:30.564906 DEBUG: NSS_DB: NSS User Database, [Installed: True, Valid: False, Reason: Multiple certificates installed at NSS User Database]
12:34:30.564925 DEBUG: CA_CERTS_FOLDER(deprecated): /usr/local/share/ca-certificates/rootCA.crt, [Installed: False, Valid: False, Reason: The certificate is not installed at /usr/local/share/ca-certificates/rootCA.crt]
12:34:30.564940 DEBUG: SSL_CERTS(deprecated): /etc/ssl/certs/rootCA.pem, [Installed: False, Valid: False, Reason: The certificate is not installed at /etc/ssl/certs/rootCA.pem]
12:34:30.564952 INFO: The installed certificate has errors: Multiple certificates installed at NSS User Database
12:34:30.565008 INFO: 	Certificate is not installed. Use gui.core.installShellWebCertificate() to install one.
```

Can this be due to past attempts to install the certificate?

**Comment by rennox** [comment]
Hi @RafaelMoreira1180778 

Yeah that is related to the previous install attempts, running the Welcome wizard again should fix it, please execute the Wizard and restart VSCode.

rennox

**Comment by RafaelMoreira1180778** [comment]
@rennox got it!

I deleted `/home/rafael/.pki` (after backing it up, of course) and re-ran the welcome wizard again. Now it's working perfectly!

Thank you for your support!
