### ISSUE TITLE
日本語データの挿入について / About inserting Japanese data

### ISSUE THREAD

**Issue by yuzuru-git** [mysql/mysql-shell-plugins#6]
hello.
When I insert Japanese data, the characters are garbled. Is there a solution?

For example ...

（sql）
INSERT into t_test(id,name) VALUES(3,'あほの酒田')
（result）
id | name
3 | ãã»ã®éç°

**Comment by rennox** [comment]
Hi @yuzuru-git 

We need to review and fix this, thanks doe bringing it up.

Would be ideal if you can help us creating a bug report.

![image](https://user-images.githubusercontent.com/1464064/173210296-21a6dd1d-ceb6-4aa5-a7d8-ec807dbafa59.png)

Will ping you once we solve this!

rennox

**Comment by yuzuru-git** [comment]
Thank you for your reply.
I send bug report as "Bug #107541".

Thank you.
![2022-06-12 11 14 16](https://user-images.githubusercontent.com/65604159/173211438-3bc308fd-b79d-4cee-a5c6-6c00b773ee6f.png)

**Comment by rennox** [comment]
@yuzuru-git 

An updated version has been released, the problem you reported should be fixed there.

Thanks for submitting the bug report!

**Comment by yuzuru-git** [comment]
@rennox 

Thank you for your prompt response!
I confirmed problem resolution.
