### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by camelogne** [mysql/mysql-shell-plugins#9]
- Issue Type: `Performance`
- Extension Name: `mysql-shell-for-vs-code`
- Extension Version: `1.3.2`
- OS Version: `Windows_NT x64 10.0.22622`
- VS Code version: `1.70.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/LSB/AppData/Local/Temp/Oracle.mysql-shell-for-vs-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mike-lischke** [comment]
@camelogne You haven't added the cpu profile file to this bug report, so we cannot check your issue. Does the heavy CPU load issue come up while loading the extension or while having one of the webview open?
